### ISSUE TITLE
Can't edit officers end times

### ISSUE THREAD

**Issue by djrenren** [rit-sse/officers#3]
:'(

**Comment by kristenmills** [comment]
What happened when you tried to do it? Did it not save? Did it save but not with the right date?

**Comment by vuzDylan** [comment]
What is wrong is that since you added the ablity to have end dates as null they now can only be null for some reason, i just fixed it but now i cant get them to set back to null (edit branch)

**Comment by kristenmills** [comment]
What do you mean they can only be null? Like if you save it with an end date change, what happens?

**Comment by kristenmills** [comment]
Update: We're figuring it out.
