### ISSUE TITLE
Can't Create new committees...

### ISSUE THREAD

**Issue by djrenren** [rit-sse/officers#4]
(Shouldn't these be derived from the officers list?)

**Comment by kristenmills** [comment]
More details please.

**Comment by kristenmills** [comment]
Also to answer your other question...not exactly. They need to be seperate entities and might not match up one to one with officers (I.E. General)

**Comment by djrenren** [comment]
We have a new officer position "Historian" who isn't reflected in the list of comittees. So when I created the position I had to list the title as "Historian" but the committee as "General"

**Comment by kristenmills** [comment]
You can create a new committee in that field. I'm going to keep this issue open though because if that's not clear, we should probably make it so.

**Comment by vuzDylan** [comment]
I was not able to create a committee using that field. how are you supposed to be able to do that?

**Comment by kristenmills** [comment]
Just type and press enter. Works on dev

**Comment by kristenmills** [comment]
Update: I had decided to not allow new committees when editing officers. This is probably not the best behavior. Can be easily fixed.
